<?php
namespace Phossa\Cache\Utility;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-20 at 08:31:59.
 */
class QuickCacheTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var QuickCache
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new QuickCache;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Phossa\Cache\Utility\QuickCache::cachedCallable
     * @todo   Implement testCachedCallable().
     */
    public function testCachedCallable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
