<?php
namespace Phossa\Cache\Driver;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-20 at 08:29:14.
 */
class NullDriverTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var NullDriver
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NullDriver;

        // cache
        $this->cache  = new \Phossa\Cache\CachePool();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Phossa\Cache\Driver\NullDriver::get
     */
    public function testGet()
    {
        $this->assertEquals(serialize(null), $this->object->get('test'));
    }

    /**
     * @covers Phossa\Cache\Driver\NullDriver::has
     */
    public function testHas()
    {
        $this->assertEquals(0, $this->object->has('test'));
    }

    /**
     * @covers Phossa\Cache\Driver\NullDriver::clear
     */
    public function testClear()
    {
        $this->assertEquals(true, $this->object->clear());
    }

    /**
     * @covers Phossa\Cache\Driver\NullDriver::delete
     */
    public function testDelete()
    {
        $this->assertEquals(true, $this->object->delete('test'));
    }

    /**
     * @covers Phossa\Cache\Driver\NullDriver::save
     */
    public function testSave()
    {
        $item = new \Phossa\Cache\CacheItem('test', $this->cache);
        $this->assertEquals(true, $this->object->save($item));
    }

    /**
     * @covers Phossa\Cache\Driver\NullDriver::saveDeferred
     */
    public function testSaveDeferred()
    {
        $item = new \Phossa\Cache\CacheItem('test', $this->cache);
        $this->assertEquals(true, $this->object->saveDeferred($item));
    }

    /**
     * @covers Phossa\Cache\Driver\NullDriver::commit
     */
    public function testCommit()
    {
        $this->assertEquals(true, $this->object->commit());
    }

    /**
     * @covers Phossa\Cache\Driver\NullDriver::purge
     */
    public function testPurge()
    {
        $this->assertEquals(true, $this->object->purge(86400));
    }
}
